### PR TITLE
[feat] add patch cmds post patch

### PR DESCRIPTION
**Pull request by Ryang20718**
feature: adds `patch_cmds` which `http_archive` currently supports.

This runs a list of commands **after** patches. 

Some use cases include, but are not limited to: 
- modifying runfile paths after a patch is done
- creating symlinks

### CODE REVIEW

**Comment by Ryang20718** [comment]
@1e100 when you have a minute, if you could take a look at this changeset, I would appreciate it very much!

**Comment by 1e100** [comment]
Ryang, could you suggest some use cases where you'd need this?

**Comment by Ryang20718** [comment]
@1e100 added some use cases as part of the PR description!

**Review by 1e100 — APPROVED** [review]

**Comment by 1e100** [comment]
Cut a new release as well, thanks for your PR

**Pull request merged**
